### ISSUE TITLE
Plugin support for 2.12 for 0.8.x

### ISSUE THREAD

**Issue by hagl** [scala-tsi/scala-tsi#282]
As far as I understand, sbt 1.x expects all plugins to be compiled with 2.12, even if the project uses a newer Scala version. 
How can the plugin be used after the removal of support 2.12 in https://github.com/scala-tsi/scala-tsi/pull/267?

If I start Sbt 1.8.2 in the example project (https://github.com/scala-tsi/scala-tsi/tree/master/example)  I get the following error:
``` 
[info] welcome to sbt 1.8.2 (Azul Systems, Inc. Java 19.0.1)
[info] Using scala-tsi 0.8.0	plugin.version=None	published=0.8.0	CI=None
[info] loading settings for project example-build from plugins.sbt ...
[info] loading project definition from /Users/harald/projects/scala-tsi/example/project
[info] Updating
[info] Resolved  dependencies
[warn]
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.scalatsi:sbt-scala-tsi:0.8.0 (sbtVersion=1.0, scalaVersion=2.12)
[warn]
[warn] 	Note: Unresolved dependencies path:
[error] sbt.librarymanagement.ResolveException: Error downloading com.scalatsi:sbt-scala-tsi;sbtVersion=1.0;scalaVersion=2.12:0.8.0
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/scalatsi/sbt-scala-tsi_2.12_1.0/0.8.0/sbt-scala-tsi-0.8.0.pom
[error]   not found: /Users/harald/.ivy2/local/com.scalatsi/sbt-scala-tsi/scala_2.12/sbt_1.0/0.8.0/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.scalatsi/sbt-scala-tsi/scala_2.12/sbt_1.0/0.8.0/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.scalatsi/sbt-scala-tsi/scala_2.12/sbt_1.0/0.8.0/ivys/ivy.xml
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:344)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:313)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:313)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:59)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:133)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:146)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:146)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:127)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:160)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$1(Defaults.scala:3687)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] 	at java.base/java.lang.Thread.run(Thread.java:1589)
[error] (update) sbt.librarymanagement.ResolveException: Error downloading com.scalatsi:sbt-scala-tsi;sbtVersion=1.0;scalaVersion=2.12:0.8.0
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/scalatsi/sbt-scala-tsi_2.12_1.0/0.8.0/sbt-scala-tsi-0.8.0.pom
[error]   not found: /Users/harald/.ivy2/local/com.scalatsi/sbt-scala-tsi/scala_2.12/sbt_1.0/0.8.0/ivys/ivy.xml
[error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.scalatsi/sbt-scala-tsi/scala_2.12/sbt_1.0/0.8.0/ivys/ivy.xml
[error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/com.scalatsi/sbt-scala-tsi/scala_2.12/sbt_1.0/0.8.0/ivys/ivy.xml

**Comment by dhoepelman** [comment]
The SBT plugin is still compiled with 2.12. This seems to be a problem with some changes I made to publishing, the plugin is published ivy instead of maven style.

![image](https://user-images.githubusercontent.com/992153/216099661-c900e771-bc12-461d-8c63-e450e1784bc8.png)

I will try to fix and release a 0.8.1

**Comment by dhoepelman** [comment]
Just released 0.8.1, should fix it. Will take a little while for it to percolate everywhere

**Comment by hagl** [comment]
Thanks a lot for the quick fix!

**Comment by dhoepelman** [comment]
0.8.1 has been released and fixed the issue for me locally, let me know if there's any more trouble.

**Comment by hagl** [comment]
Version 0.8.1 works fine in my project too! Thanks again!
